apiVersion: v1
kind: Namespace
metadata:
  name: phantom-ai
  labels:
    app.kubernetes.io/name: phantom-ai
    managed-by: argocd
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/audit: baseline
